openapi: 3.0.3
info:
  title: Wave Dealer API
  version: 1.0.0
  description: API for Wave Dealer service

servers:
  - url: /api/wave-dealer

paths:
  /youtube:
    post:
      summary: Submit a youtube song request
      operationId: requestYoutubeSong
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/YoutubeSongRequestBody"
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:    
    YoutubeSongRequestBody:
      type: object
      required:
      - url
      properties:
        url:
          type: string
          format: uri
